[package]
name = "test-cot-0_4"
version = "0.1.0"
edition = "2021"
publish = false

[dev-dependencies]
askama = { workspace = true, features = ["derive"] }
askama_web = { workspace = true, features = ["derive", "cot-0.4"] }

cot = { version = "0.4.0", features = ["test"] }
