[package]
name = "test-cot-0_3"
version = "0.1.0"
edition = "2024"
publish = false

[dev-dependencies]
askama = { workspace = true, features = ["derive"] }
askama_web = { workspace = true, features = ["derive", "cot-0.3"] }

cot = { version = "0.3.0", features = ["test"] }
