[package]
name = "test-rocket-0_5"
version = "0.0.1-pre.0"
edition = "2021"
publish = false

[dev-dependencies]
askama = "0.12.1"
askama_web = { path = "../askama_web", version = "0.0.1-pre.0", features = ["rocket-0.5"] }

rocket = { version = "0.5.1", default-features = false }
